# Generated by Django 5.1.4 on 2025-06-10 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university_link', models.URLField(blank=True, null=True)),
                ('slogan', models.TextField()),
                ('acronime', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university/logo/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UnverifiedUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('type', models.CharField(default='standard', max_length=50)),
                ('realisation_linkedin', models.URLField(blank=True, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('password', models.CharField(max_length=255)),
                ('verification_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailv', models.EmailField(max_length=254)),
                ('datev', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('annee_publication', models.PositiveIntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='memoires/images/')),
                ('resume', models.TextField()),
                ('fichier_memoire', models.FileField(upload_to='memoires/pdf/')),
                ('domaines', models.ManyToManyField(related_name='memoires', to='memoire.domaine')),
                ('universites', models.ManyToManyField(blank=True, related_name='memoires', to='memoire.university')),
            ],
        ),
        migrations.CreateModel(
            name='Telechargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailt', models.EmailField(max_length=254)),
                ('datet', models.DateTimeField(auto_now_add=True)),
                ('memoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telechargements', to='memoire.memoire')),
            ],
        ),
        migrations.AddField(
            model_name='domaine',
            name='universites',
            field=models.ManyToManyField(blank=True, related_name='domaines', to='memoire.university'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('admin', 'Administrateur'), ('superadmin', 'Super Administrateur'), ('bigboss', 'BIGBOSS')], default='standard', max_length=10)),
                ('realisation_linkedin', models.URLField(blank=True, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photos_profil/')),
                ('password', models.CharField(max_length=128)),
                ('universites', models.ManyToManyField(blank=True, related_name='utilisateurs', to='memoire.university')),
            ],
        ),
        migrations.AddField(
            model_name='memoire',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoires', to='memoire.userprofile'),
        ),
        migrations.CreateModel(
            name='Encadrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encadrements', to='memoire.memoire')),
                ('encadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encadrements', to='memoire.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NotationCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('note', models.PositiveIntegerField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('memoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations', to='memoire.memoire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations', to='memoire.userprofile')),
            ],
            options={
                'unique_together': {('memoire', 'utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='UserUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('etudiant', 'Étudiant'), ('professeur', 'Professeur'), ('admin', 'Administrateur'), ('superadmin', 'SUPERAdministrateur'), ('autre', 'Autre')], max_length=50)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_users', to='memoire.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_universities', to='memoire.userprofile')),
            ],
            options={
                'unique_together': {('user', 'university')},
            },
        ),
    ]
