# Generated by Django 5.1.4 on 2025-02-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaine',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
