# Generated by Django 5.1.3 on 2024-12-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
