# Generated by Django 5.1.3 on 2024-12-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0002_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('admin', 'Administrateur'), ('superadmin', 'superAdministrateur')], default='standard', max_length=10),
        ),
    ]
