# Generated by Django 5.1.4 on 2024-12-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0003_actionhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionHistory',
        ),
    ]
