# Generated by Django 5.1.3 on 2024-12-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0003_alter_userprofile_password_alter_userprofile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unverifieduserprofile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='unverifieduserprofile',
            name='type',
            field=models.CharField(default='standard', max_length=50),
        ),
    ]
