# Generated by Django 5.1.3 on 2024-12-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0004_remove_unverifieduserprofile_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('annee_publication', models.PositiveIntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='memoires/images/')),
                ('datet', models.DateTimeField(auto_now_add=True)),
                ('resume', models.TextField()),
                ('state', models.CharField(choices=[('E', 'ENCOURS'), ('P', 'PASSER')], max_length=1)),
            ],
        ),
    ]
