# Generated by Django 5.1.3 on 2024-12-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0005_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
