# Generated by Django 5.1.4 on 2025-01-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0006_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university_link', models.URLField(blank=True, null=True)),
                ('slogan', models.TextField()),
                ('acronime', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university/logo/')),
                ('description', models.TextField()),
            ],
        ),
    ]
