# Generated by Django 5.1.4 on 2025-02-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0007_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='acronime',
            field=models.CharField(max_length=200),
        ),
    ]
