# Generated by Django 5.1.4 on 2025-02-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0008_alter_university_acronime'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='universites',
            field=models.ManyToManyField(blank=True, related_name='memoires', to='memoire.university'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='universites',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='memoire.university'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('admin', 'Administrateur'), ('superadmin', 'Super Administrateur')], default='standard', max_length=10),
        ),
    ]
