# Generated by Django 5.1.4 on 2025-02-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0009_memoire_universites_userprofile_universites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoire',
            name='universites',
            field=models.ManyToManyField(related_name='memoires', to='memoire.university'),
        ),
    ]
