# Generated by Django 5.1.4 on 2025-02-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0010_alter_memoire_universites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoire',
            name='universites',
            field=models.ManyToManyField(blank=True, related_name='memoires', to='memoire.university'),
        ),
    ]
