# Generated by Django 5.1.4 on 2025-02-05 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0011_alter_memoire_universites'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('etudiant', 'Étudiant'), ('professeur', 'Professeur'), ('admin', 'Administrateur'), ('autre', 'Autre')], max_length=50)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_users', to='memoire.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_universities', to='memoire.userprofile')),
            ],
            options={
                'unique_together': {('user', 'university')},
            },
        ),
    ]
