# Generated by Django 5.1.4 on 2025-02-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0012_useruniversity'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='universites',
            field=models.ManyToManyField(blank=True, related_name='domaines', to='memoire.university'),
        ),
    ]
